spring.application.name=todotask
spring.datasource.url=jdbc:postgresql://localhost:5432/todotask_db
spring.datasource.username=serggalel
spring.datasource.password=strong_pass
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
