spring.application.name=todotask
spring.datasource.url=jdbc:postgresql://localhost:5432/todotask
spring.datasource.username=serggalel
spring.datasource.password=$tr0ng_p@ss
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
